# docker-compose.yml
version: '3.8'
services:
  alpr:
    build: ./openalpr-upload
    user: root
    volumes:
      - ./goalpr/assets/images:/var/lib/openalpr/plateimages      
networks:
  redis-network:
    driver: bridge      